apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ai-studio
spec:
  to:
    kind: Service
    name: ai-studio
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
